server:
#  port: 8090         #修改端口
  tomcat:
    uri-encoding: utf-8   #修改tomcat字符集

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo?characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect